services:
  mysql:
    image: mysql:8.4
    container_name: seckill-go-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "200143"
      MYSQL_DATABASE: "seckill_demo"
    ports:
      - "3308:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_go_data:/var/lib/mysql

volumes:
  mysql_go_data:
